# Generated by Django 3.2.25 on 2024-06-14 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='WeatherStation',
        ),
    ]
