# Generated by Django 3.2.25 on 2024-06-14 16:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0003_auto_20240614_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('bus_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ski_resort_grp1.busstation')),
                ('lift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ski_resort_grp1.skilift')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ski_resort_grp1.restaurant')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ski_resort_grp1.skiroute')),
            ],
        ),
    ]
