# Generated by Django 3.2.25 on 2024-06-14 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0004_mainpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainPoint',
        ),
    ]
