# Generated by Django 3.2.25 on 2024-06-16 21:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0007_alter_skiroute_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
