# Generated by Django 3.2.25 on 2024-06-16 21:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0008_alter_restaurant_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
