# Generated by Django 3.2.25 on 2024-06-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0011_auto_20240622_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestation',
            name='schedule',
            field=models.CharField(default='08:00 - 16:00', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basestation',
            name='type',
            field=models.CharField(default='Start', max_length=50),
            preserve_default=False,
        ),
    ]
