# Generated by Django 3.2.25 on 2024-06-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0012_auto_20240622_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilift',
            name='state',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
