# Generated by Django 3.2.25 on 2024-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_resort_grp1', '0013_skilift_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilift',
            name='direction',
            field=models.CharField(choices=[('up', 'Up')], default='Up', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skiroute',
            name='direction',
            field=models.CharField(choices=[('down', 'Down')], default='Down', max_length=10),
            preserve_default=False,
        ),
    ]
